name: Feature pull request
description: Create a pull request that adds a new feature to the project.
title: "[Feature]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks in advance for your contribution to Discord.Net!
        Before opening a pull request, please consider the following:
        Does your changeset adhere to the Contributing Guidelines?
        Does your changeset address a specific issue or idea? If not, please break your changes up into multiple requests.
        Have your changes been previously discussed with other members of the community? 
        We prefer new features to be vetted through an issue or a discussion in our Discord channel first; 
        bug-fixes and other small changes are generally fine without prior vetting.
- type: textarea
  id: description
  attributes:
    label: Description
    description: A brief explanation of the feature(s) added in this PR.
    placeholder: This PR adds the new feature released by Discord.
  validations:
    required: true
- type: Changes
  id: changes
  attributes:
    label: Changes
    description: List things changed in this pull request.
    placeholder: |
      Add X entity
      Update Y method
  validations:
    required: true
- type: textarea
  id: issues
  attributes:
    label: Related issue
    description: List issues that are related to this PR.
    placeholder: "- resolves #6969 "
  validations:
    required: false
